/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AppSettings {
  fontFamily: string
  editorPadding: string
  fontSize?: string
  lineSpacing?: string
  backupSnapshotMode?: string
  /**
   * How many snapshots to keep. Oldest beyond this are deleted after each
   * new snapshot. 0 disables snapshots entirely.
   */
  backupSnapshotKeep?: number
}

export declare function backupOnQuit(vaultPath: string): Promise<void>

/**
 * A single line-level hit from a full-text content search: which file, which
 * line (1-indexed, for display), the line's text (for the snippet), and the
 * UTF-16 code-unit offset within that line where the match starts, so the
 * frontend can highlight it without re-running its own search.
 */
export interface ContentSearchMatch {
  path: string
  name: string
  lineNumber: number
  lineText: string
  matchStart: number
  matchLen: number
}

export declare function copyFileOrFolder(sourcePath: string): string

export declare function createNewFile(parentPath: string, fileName: string): string

export declare function createNewFolder(parentPath: string, folderName: string): string

export declare function createVaultDirectory(): string

export declare function deleteFileOrFolder(targetPath: string): void

export interface FileMeta {
  size: number
  created?: number
  modified?: number
}

export interface FileNode {
  name: string
  path: string
  isDir: boolean
  size: number
  children?: Array<FileNode>
}

export declare function getFileMeta(filePath: string): FileMeta

export declare function getFileTree(vaultPath: string): Array<FileNode>

export declare function jsLog(msg: string): void

export declare function listBackupSnapshots(vaultPath: string): Array<SnapshotInfo>

export declare function loadSettings(vaultPath: string): AppSettings

export declare function openExternalUrl(url: string): void

export declare function readFileContent(filePath: string): string

export declare function readImageBase64(filePath: string): string

export declare function renameFileOrFolder(oldPath: string, newPath: string): void

export declare function restoreFromTrash(originalPath: string): void

export declare function restoreSnapshot(vaultPath: string, snapshotPath: string): Promise<void>

export declare function saveFontByPath(sourcePath: string, fileName: string): string

export declare function saveSettings(vaultPath: string, settings: AppSettings): void

/**
 * Case-insensitive full-text search across every text document in the
 * vault. Reads each candidate file, scans it line by line, and returns one
 * `ContentSearchMatch` per matching line (a line with the query appearing
 * twice still yields a single row — this powers "jump to this line", not an
 * exhaustive occurrence count).
 */
export declare function searchContentInVault(vaultPath: string, query: string): Array<ContentSearchMatch>

export declare function searchFileTree(vaultPath: string, query: string): Array<SearchMatch>

/**
 * A single file/folder search hit. `match_indices` lists the UTF-16 code
 * unit positions within `name` that actually matched the query — not a
 * start/end span — so a fuzzy match like "개방" against "개선방안" highlights
 * only the "개" and "방" characters, not everything in between. `score`
 * orders results: lower is better (exact/prefix/contiguous matches outrank
 * scattered fuzzy ones).
 */
export interface SearchMatch {
  name: string
  path: string
  isDir: boolean
  matchIndices: Array<number>
  score: number
}

export declare function showInFolder(targetPath: string): void

export interface SnapshotInfo {
  /**
   * Bare filename, e.g. vault_2026-07-14_183012.7z or vault_2026-07-14.7z.
   * The renderer parses the timestamp out of this for display.
   */
  name: string
  /** Absolute path, handed back verbatim to restore_snapshot. */
  path: string
  /** Archive size in bytes. */
  size: number
  /** mtime, seconds since the epoch (display only). */
  modified: number
}

export declare function startVaultWatcher(vaultPath: string, callback: ((err: Error | null, ) => void)): void

export declare function writeFileContent(vaultPath: string, filePath: string, content: string): void
